config/routes.rb
Rails.application.routes.draw do

  resources :articles

  root 'welcome#index'

  get 'html/testing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
<<<<<<< HEAD
  validates :title, presence: true,
                  length: { minimum: 1 }
=======
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
<<<<<<< HEAD

=======
  
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4
  def new
  end

  def create
    @article = Article.new(article_params)
<<<<<<< HEAD

=======
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4
    @article.save
    redirect_to @article
  end

  def show
   @article = Article.find(params[:id])
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end

end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
  def testing
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/html_helper.rb
module HtmlHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<<<<<<< HEAD
<% @title = 'Listing articles' %>

<h1>Listing articles</h1>

<%= link_to 'New article', new_article_url %>
<br />
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td>
        <% if article.title.length > 13 %>
          <%= article.title[0...12].concat('...') %>
        <% else %>
          <%= article.title %>
        <% end %>
      </td>

      <td>
        <% if article.text.length > 10 %>
          <%= article.text[0...9].concat('...') %>
        <% else %>
          <%= article.text %>
        <% end %>
      </td>

      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>
=======
<h1>Listing articles</h1>

<%= link_to 'New article', new_article_url %>
<br />
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4

app/views/articles/new.html.erb
<<<<<<< HEAD
<% @title = 'New Article' %>

<h1> New Article </h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
=======
<h1> New Article </h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4

app/views/articles/show.html.erb
<<<<<<< HEAD
<% @title = 'View Article' %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
  <br />
  <br />
  <%= link_to 'Back to article list', articles_url %>
</p>
=======
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4

app/views/html/testing.html.erb
<title> HTML testing </title>
<h1> This page is dedicated to testing out html code. </h1>

<body>
  <p> This is body text. </p>
</body>

<button type="button"> Button </button>
<p></p>
<code> System.exit(0); </code>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <%= favicon_link_tag 'icon.ico' %>
    <title> <%= @title %> </title>
=======
    <title>Blog</title>
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<<<<<<< HEAD
<% @title = 'Yummy\'s App!' %>

=======
>>>>>>> a30d25ca2d369b8970beb0796fa33825e04dadc4
<h1> Welcome to Yummy's Development App! </h1>
  <p> This site is meant for testing, which is why it will mainly not be anywhere but
      locally on Yummy's PC.
      <br />
      <br />
    Here's a link to the Blog page:
    <%= link_to 'Yummy\'s Blog', articles_url %>

  </p>